export const surahDescriptions: Record<number, { desc: string; ref: string }> = {
  1: { desc: "The opening chapter of the Quran, emphasizing praise for Allah, His lordship, and a prayer for guidance on the straight path.", ref: "https://quran.com/1" },
  2: { desc: "The longest Surah, named after the story of the Israelites and the Cow. It covers comprehensive laws, guidance for believers, and the stories of past nations.", ref: "https://quran.com/2" },
  3: { desc: "Focuses on the oneness of God, the story of Mary and Jesus, and the Battle of Uhud, emphasizing steadfastness in faith.", ref: "https://quran.com/3" },
  4: { desc: "Addresses social issues, inheritance laws, women's rights, and the importance of justice and family within the community.", ref: "https://quran.com/4" },
  5: { desc: "Discusses dietary laws, contracts, the finality of the religion, and the relationship between Muslims and People of the Book.", ref: "https://quran.com/5" },
  6: { desc: "Emphasizes monotheism, Allah's creative power, and the refutation of polytheism through logical arguments.", ref: "https://quran.com/6" },
  7: { desc: "Recounts stories of previous prophets to warn against arrogance and the consequences of rejecting God's message.", ref: "https://quran.com/7" },
  8: { desc: "Discusses the Battle of Badr, the distribution of war booty, and the qualities of true believers during times of conflict.", ref: "https://quran.com/8" },
  9: { desc: "The only Surah that does not begin with 'Bismillah.' It deals with the breaking of treaties, the Battle of Tabuk, and the distinction between true believers and hypocrites.", ref: "https://quran.com/9" },
  10: { desc: "Highlights Allah's power in creation and the stories of past prophets, particularly Jonah, to emphasize the truth of revelation.", ref: "https://quran.com/10" },
  11: { desc: "Focuses on the stories of several prophets to warn against the consequences of rejecting God's messengers and the importance of repentance.", ref: "https://quran.com/11" },
  12: { desc: "Narrates the comprehensive story of Prophet Joseph, illustrating patience, trust in God, and eventual success despite hardship.", ref: "https://quran.com/12" },
  13: { desc: "Discusses Allah's power in nature and the truth of revelation, emphasizing that hearts find rest in the remembrance of God.", ref: "https://quran.com/13" },
  14: { desc: "Highlights the message of Prophet Abraham and the importance of gratitude and monotheism for individual and social success.", ref: "https://quran.com/14" },
  15: { desc: "Warns those who mock the prophets and highlights Allah's protection of the Quran from any corruption.", ref: "https://quran.com/15" },
  16: { desc: "Mentions various blessings of Allah in nature, such as the bee, as signs of His wisdom and providence for humanity.", ref: "https://quran.com/16" },
  17: { desc: "Narrates the Night Journey of Prophet Muhammad and provides ethical guidelines for individual and social life.", ref: "https://quran.com/17" },
  18: { desc: "Features stories like the People of the Cave, Moses with Khidr, and Dhul-Qarnayn, emphasizing faith, humility, and protection from the trials of the end times.", ref: "https://quran.com/18" },
  19: { desc: "Tells the stories of Zechariah, John the Baptist, Mary, and Jesus, emphasizing God's mercy, power, and the message of monotheism.", ref: "https://quran.com/19" },
  20: { desc: "Focuses on the story of Moses and his encounter with Pharaoh, offering comfort and encouragement to Prophet Muhammad.", ref: "https://quran.com/20" },
  21: { desc: "Highlights that all prophets brought the same message of monotheism and warns of the impending Day of Judgment for all.", ref: "https://quran.com/21" },
  22: { desc: "Discusses the pilgrimage to Mecca (Hajj), the importance of sacrifice, and the eventual triumph of truth over falsehood.", ref: "https://quran.com/22" },
  23: { desc: "Describes the characteristics of successful believers and the miraculous stages of human creation as signs of Allah.", ref: "https://quran.com/23" },
  24: { desc: "Addresses the incident of the slander against Aisha (RA), establishes laws regarding modesty and privacy, and features the famous 'Verse of Light.'", ref: "https://quran.com/24" },
  25: { desc: "Distinguishes between truth and falsehood (the Criterion) and describes the qualities of the humble 'Servants of the Most Merciful.'", ref: "https://quran.com/25" },
  26: { desc: "Highlights the stories of various prophets to show that their message was rejected by the arrogant, leading to their downfall.", ref: "https://quran.com/26" },
  27: { desc: "Features the stories of Solomon, the Queen of Sheba, and the ants, highlighting Allah's signs in nature, His absolute power, and the need for gratitude.", ref: "https://quran.com/27" },
  28: { desc: "Focuses on the detailed story of Moses from birth to prophethood, illustrating God's support for the oppressed against tyrants.", ref: "https://quran.com/28" },
  29: { desc: "Emphasizes that faith is tested, comparing reliance on anything other than Allah to a flimsy spider's web, and calls for steadfastness in persecution.", ref: "https://quran.com/29" },
  30: { desc: "Predicts the victory of the Romans and highlights Allah's signs in the creation of the heavens, the earth, and human diversity.", ref: "https://quran.com/30" },
  31: { desc: "Contains the wise advice given by Luqman to his son, emphasizing monotheism, gratitude, and maintaining good conduct.", ref: "https://quran.com/31" },
  32: { desc: "Discusses the creation of man, the Day of Judgment, and the importance of prostration and night worship.", ref: "https://quran.com/32" },
  33: { desc: "Deals with the Battle of the Trench and provides social regulations for the Prophet's household and the early Muslim community.", ref: "https://quran.com/33" },
  34: { desc: "Highlights the power of Allah and the stories of David and Solomon, warning against ungratefulness and the vanity of worldly power.", ref: "https://quran.com/34" },
  35: { desc: "Emphasizes Allah as the Originator of all things and His absolute power and independence from His creation.", ref: "https://quran.com/35" },
  36: { desc: "Traditionally revered as the 'Heart of the Quran,' it focuses powerfully on the truth of revelation, the reality of the Resurrection, and the signs of nature.", ref: "https://quran.com/36" },
  37: { desc: "Discusses the ranks of angels and the stories of various prophets to emphasize monotheism and the rejection of idols.", ref: "https://quran.com/37" },
  38: { desc: "Focuses on the stories of David, Solomon, and Job, highlighting their patience, devotion, and frequent turning to Allah.", ref: "https://quran.com/38" },
  39: { desc: "Emphasizes pure monotheism and the different fates of believers and disbelievers on the Day of Judgment.", ref: "https://quran.com/39" },
  40: { desc: "Highlights Allah's forgiveness and power, recounting the story of a believer in Pharaoh's court who stood for truth.", ref: "https://quran.com/40" },
  41: { desc: "Discusses the clarity of the Quran and the importance of inviting others to Allah with wisdom, patience, and good character.", ref: "https://quran.com/41" },
  42: { desc: "Emphasizes consultation (shura) among believers and the central message of all prophets being the same path of faith.", ref: "https://quran.com/42" },
  43: { desc: "Criticizes the obsession with worldly wealth and highlights the truth of revelation through the examples of past prophets.", ref: "https://quran.com/43" },
  44: { desc: "Warns of a coming 'Smoke' as a sign of judgment and recounts the story of Moses and Pharaoh as a lesson for the arrogant.", ref: "https://quran.com/44" },
  45: { desc: "Discusses the signs of Allah in nature and the consequences for those who arrogantly reject His message and guidance.", ref: "https://quran.com/45" },
  46: { desc: "Warns of the punishment that befell the people of 'Ad and emphasizes the importance of honoring parents and being grateful.", ref: "https://quran.com/46" },
  47: { desc: "Focuses on the qualities of believers, the importance of striving in Allah's cause, and the ultimate victory of truth over falsehood.", ref: "https://quran.com/47" },
  48: { desc: "Celebrates the 'Clear Victory' of the Treaty of Hudaybiyyah and the strength and loyalty of the Muslim community.", ref: "https://quran.com/48" },
  49: { desc: "Provides ethical guidelines for social conduct, emphasizing brotherhood, respect, and the avoidance of gossip and suspicion.", ref: "https://quran.com/49" },
  50: { desc: "Emphasizes the reality of the Resurrection and the Day of Judgment through signs in nature and the history of past nations.", ref: "https://quran.com/50" },
  51: { desc: "Highlights Allah's power in creation and the certainty of His promise regarding the Day of Judgment and rewards.", ref: "https://quran.com/51" },
  52: { desc: "Swears by various sacred sites to emphasize the reality of the punishment for disbelievers and the reward for the righteous.", ref: "https://quran.com/52" },
  53: { desc: "Discusses the Prophet's ascension and refutes polytheistic beliefs about angels and idols, emphasizing individual accountability.", ref: "https://quran.com/53" },
  54: { desc: "Warns of the approaching Day of Judgment by recounting the destruction of past nations who rejected their prophets' messages.", ref: "https://quran.com/54" },
  55: { desc: "Addresses both mankind and Jinn, repetitively asking 'Which of the favors of your Lord will you deny?' while describing Allah's infinite blessings and mercy.", ref: "https://quran.com/55" },
  56: { desc: "Describes the 'Inevitable Event' of Judgment Day and the three groups people will be divided into based on their deeds.", ref: "https://quran.com/56" },
  57: { desc: "Emphasizes Allah's sovereignty and encourages believers to spend in His cause, remain humble, and seek His light.", ref: "https://quran.com/57" },
  58: { desc: "Addresses the plea of a woman who complained to the Prophet and provides rules regarding secret counsels and social conduct.", ref: "https://quran.com/58" },
  59: { desc: "Discusses the exile of the Banu Nadir and the distribution of war booty, highlighting Allah's beautiful names and attributes.", ref: "https://quran.com/59" },
  60: { desc: "Provides guidance on dealing with relatives who remain polytheists and the testing of women who migrate for the sake of faith.", ref: "https://quran.com/60" },
  61: { desc: "Encourages believers to strive in Allah's cause in organized ranks and highlights the prophecy of Jesus regarding the coming of Ahmad.", ref: "https://quran.com/61" },
  62: { desc: "Discusses the importance of the Friday prayer (Jumu'ah) and the responsibility of the community to uphold and practice the message.", ref: "https://quran.com/62" },
  63: { desc: "Exposes the characteristics and deceit of hypocrites within the Muslim community and warns against their influence.", ref: "https://quran.com/63" },
  64: { desc: "Describes the Day of Judgment as a day of 'Mutual Loss and Gain' and emphasizes trust in Allah and patience in trials.", ref: "https://quran.com/64" },
  65: { desc: "Provides detailed regulations regarding divorce and the importance of fearing Allah and maintaining justice in all matters.", ref: "https://quran.com/65" },
  66: { desc: "Addresses the Prophet's household and sets examples for believers by contrasting the wives of Noah and Lot with the righteous wife of Pharaoh and Mary.", ref: "https://quran.com/66" },
  67: { desc: "Emphasizes Allah's absolute sovereignty over the universe and His power to give life and death as a test for humanity.", ref: "https://quran.com/67" },
  68: { desc: "Defends the character of Prophet Muhammad and warns of the consequences of greed, arrogance, and rejecting the truth.", ref: "https://quran.com/68" },
  69: { desc: "Describes the 'Sure Reality' of the Day of Judgment and the fate of those who rejected the truth and the messengers.", ref: "https://quran.com/69" },
  70: { desc: "Discusses the 'Ways of Ascent' and the nature of human impatience, highlighting the qualities of those who are steadfast in prayer.", ref: "https://quran.com/70" },
  71: { desc: "Recounts the story of Prophet Noah and his persistent, multi-generational efforts to call his people to monotheism.", ref: "https://quran.com/71" },
  72: { desc: "Describes a group of Jinn who heard the Quran and accepted Islam, highlighting the oneness of Allah and the truth of revelation.", ref: "https://quran.com/72" },
  73: { desc: "Instructs the Prophet on the importance of night prayer and patience in the face of opposition and heavy responsibility.", ref: "https://quran.com/73" },
  74: { desc: "Commands the Prophet to arise and warn the people, emphasizing the importance of purification, faith, and the Day of Judgment.", ref: "https://quran.com/74" },
  75: { desc: "Focuses on the certainty of the Resurrection and the state of the human soul at the time of death and accountability.", ref: "https://quran.com/75" },
  76: { desc: "Describes the creation of man and the magnificent rewards awaiting the righteous and the grateful in Paradise.", ref: "https://quran.com/76" },
  77: { desc: "Swears by the 'Winds Sent Forth' to emphasize the reality and justice of the Day of Judgment.", ref: "https://quran.com/77" },
  78: { desc: "Discusses the 'Great News' of the Resurrection and provides vivid descriptions of both Paradise and Hell.", ref: "https://quran.com/78" },
  79: { desc: "Describes the angels who pull out souls and the overwhelming nature of the Day of Judgment and the Resurrection.", ref: "https://quran.com/79" },
  80: { desc: "Rebukes the Prophet for turning away from a blind man, emphasizing that the Quran is a reminder and guidance for everyone.", ref: "https://quran.com/80" },
  81: { desc: "Describes the cataclysmic events that will occur at the end of the world and the beginning of the Resurrection.", ref: "https://quran.com/81" },
  82: { desc: "Highlights the shattering of the sky on the Day of Judgment and the accountability of every soul for its deeds and actions.", ref: "https://quran.com/82" },
  83: { desc: "Warns those who give short measure in trade and describes the records of the righteous and the wicked in the hereafter.", ref: "https://quran.com/83" },
  84: { desc: "Describes the splitting of the sky on the Day of Judgment and the ultimate return and accountability of all beings to Allah.", ref: "https://quran.com/84" },
  85: { desc: "Recounts the story of the 'People of the Ditch' to inspire patience, steadfastness, and faith under persecution.", ref: "https://quran.com/85" },
  86: { desc: "Highlights Allah's power in creation and His ability to bring the dead back to life for judgment.", ref: "https://quran.com/86" },
  87: { desc: "Glorifies the 'Most High' and mentions that the core message is found in the earlier scriptures of Abraham and Moses.", ref: "https://quran.com/87" },
  88: { desc: "Describes the 'Overwhelming Event' of Judgment Day and the contrasting fates of the dwellers of Paradise and Hell.", ref: "https://quran.com/88" },
  89: { desc: "Mentions the destruction of past arrogant nations and emphasizes the peace of the soul that is content with Allah's will.", ref: "https://quran.com/89" },
  90: { desc: "Describes the 'City' of Mecca and the challenges of the human path, emphasizing the importance of charity, compassion, and faith.", ref: "https://quran.com/90" },
  91: { desc: "Uses various natural phenomena to swear that true success comes to those who purify their souls through faith and good deeds.", ref: "https://quran.com/91" },
  92: { desc: "Contrasts those who give and fear Allah with those who are greedy and think themselves self-sufficient and independent of God.", ref: "https://quran.com/92" },
  93: { desc: "Offers comfort and reassurance to the Prophet, reminding him of Allah's past favors and promising better things to come.", ref: "https://quran.com/93" },
  94: { desc: "Provides encouragement to the Prophet by mentioning how Allah eased his burdens, raised his status, and that ease follows hardship.", ref: "https://quran.com/94" },
  95: { desc: "Highlights the dignity and perfection of human creation and the importance of faith and righteous deeds to maintain that status.", ref: "https://quran.com/95" },
  96: { desc: "Contains the first revealed verses of the Quran, emphasizing reading, seeking knowledge, and man's total dependence on Allah.", ref: "https://quran.com/96" },
  97: { desc: "Celebrates the 'Night of Power' when the Quran was first revealed, which is described as being better than a thousand months.", ref: "https://quran.com/97" },
  98: { desc: "Discusses the 'Clear Evidence' (the Quran and the Prophet) and the state of those who reject or accept the truth.", ref: "https://quran.com/98" },
  99: { desc: "Describes the final earthquake of the Earth and the disclosure of all human deeds, however small, on the Day of Judgment.", ref: "https://quran.com/99" },
  100: { desc: "Uses the imagery of charging warhorses to highlight human ingratitude and the preoccupation with worldly wealth and power.", ref: "https://quran.com/100" },
  101: { desc: "Describes the 'Striking Calamity' of Judgment Day when people will be like scattered moths and mountains like carded wool.", ref: "https://quran.com/101" },
  102: { desc: "Criticizes the competition for worldly increase and accumulation that distracts people from their purpose until they reach their graves.", ref: "https://quran.com/102" },
  103: { desc: "Declares that all of humanity is in a state of loss except those who have faith, do good, and encourage truth and patience.", ref: "https://quran.com/103" },
  104: { desc: "Warns those who slander others and hoard wealth, thinking that their worldly possessions will make them immortal.", ref: "https://quran.com/104" },
  105: { desc: "Recounts the miraculous destruction of the 'People of the Elephant' who tried to attack the Kaaba in Mecca.", ref: "https://quran.com/105" },
  106: { desc: "Reminds the tribe of Quraysh of Allah's favors, such as their safe trade journeys, and calls them to worship the Lord of the Kaaba.", ref: "https://quran.com/106" },
  107: { desc: "Criticizes those who neglect the orphans and the poor while performing their prayers only for show and without sincerity.", ref: "https://quran.com/107" },
  108: { desc: "Promises the Prophet 'Abundance' (Al-Kawthar) and instructs him to pray and sacrifice in gratitude to Allah.", ref: "https://quran.com/108" },
  109: { desc: "Declares a clear and uncompromising distinction between the worship of Muslims and the worship of those who reject the truth.", ref: "https://quran.com/109" },
  110: { desc: "Announces the 'Help of Allah' and the coming of victory, instructing the Prophet to glorify Allah and seek His forgiveness.", ref: "https://quran.com/110" },
  111: { desc: "Condemns Abu Lahab and his wife for their fierce opposition to the Prophet Muhammad and his message of Islam.", ref: "https://quran.com/111" },
  112: { desc: "A profound declaration of pure monotheism, described by the Prophet as equivalent to one-third of the Quran, emphasizing that Allah is One and Eternal.", ref: "https://quran.com/112" },
  113: { desc: "A prayer for protection from the various evils of creation, the darkness of the night, and the harm of envious people.", ref: "https://quran.com/113" },
  114: { desc: "A prayer for protection from the whisperings of Satan and the evil inclinations within humans and Jinn.", ref: "https://quran.com/114" }
};
