import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from "react";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Quran Tracker',
  description: 'Generated by create next app',
    icons: {
        icon: '/icon.png',
    }
}

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode
}>) {
  return (
      <ClerkProvider>
        <html lang="en">
        <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#fdfaf3] text-stone-900`}>
        <header className="bg-teal-900 text-amber-50 shadow-md">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
            <h1 className="text-2xl font-bold tracking-tight text-amber-400">Quran Tracker</h1>
              <div className="flex items-center gap-4" suppressHydrationWarning>
              <SignedOut>
                <div className="flex gap-2">
                  <SignInButton mode="modal">
                    <button className="text-sm font-medium hover:text-amber-400 transition-colors">Sign In</button>
                  </SignInButton>
                  <SignUpButton mode="modal">
                    <button className="text-sm font-medium bg-amber-600 hover:bg-amber-500 px-3 py-1.5 rounded-md transition-colors text-white">Sign Up</button>
                  </SignUpButton>
                </div>
              </SignedOut>
              <SignedIn>
                <UserButton afterSignOutUrl="/" />
              </SignedIn>
            </div>
          </div>
        </header>
        <main className="min-h-screen">
          {children}
        </main>
        <footer className="py-8 text-center text-stone-500 text-sm">
          <p>© {new Date().getFullYear()} Quran Tracker • Ramadan Kareem</p>
        </footer>
        </body>
        </html>
      </ClerkProvider>
  )
}
